// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: reservas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reserva struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone       string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	PartySize   int32  `protobuf:"varint,3,opt,name=party_size,json=partySize,proto3" json:"party_size,omitempty"`
	Preferences string `protobuf:"bytes,4,opt,name=preferences,proto3" json:"preferences,omitempty"`
}

func (x *Reserva) Reset() {
	*x = Reserva{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservas_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reserva) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reserva) ProtoMessage() {}

func (x *Reserva) ProtoReflect() protoreflect.Message {
	mi := &file_reservas_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reserva.ProtoReflect.Descriptor instead.
func (*Reserva) Descriptor() ([]byte, []int) {
	return file_reservas_proto_rawDescGZIP(), []int{0}
}

func (x *Reserva) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Reserva) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Reserva) GetPartySize() int32 {
	if x != nil {
		return x.PartySize
	}
	return 0
}

func (x *Reserva) GetPreferences() string {
	if x != nil {
		return x.Preferences
	}
	return ""
}

type LoteReservas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reservas []*Reserva `protobuf:"bytes,1,rep,name=reservas,proto3" json:"reservas,omitempty"`
}

func (x *LoteReservas) Reset() {
	*x = LoteReservas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservas_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoteReservas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoteReservas) ProtoMessage() {}

func (x *LoteReservas) ProtoReflect() protoreflect.Message {
	mi := &file_reservas_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoteReservas.ProtoReflect.Descriptor instead.
func (*LoteReservas) Descriptor() ([]byte, []int) {
	return file_reservas_proto_rawDescGZIP(), []int{1}
}

func (x *LoteReservas) GetReservas() []*Reserva {
	if x != nil {
		return x.Reservas
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservas_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_reservas_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_reservas_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResultadoReserva struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PartySize     int32  `protobuf:"varint,2,opt,name=party_size,json=partySize,proto3" json:"party_size,omitempty"`
	RequestedPref string `protobuf:"bytes,3,opt,name=requested_pref,json=requestedPref,proto3" json:"requested_pref,omitempty"`
	Status        string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                     // "exitoso" | "fallido"
	MesaId        string `protobuf:"bytes,5,opt,name=mesa_id,json=mesaId,proto3" json:"mesa_id,omitempty"`       // si exitoso
	Motivo        string `protobuf:"bytes,6,opt,name=motivo,proto3" json:"motivo,omitempty"`                     // si fallido
	MesaTipo      string `protobuf:"bytes,7,opt,name=mesa_tipo,json=mesaTipo,proto3" json:"mesa_tipo,omitempty"` // tipo final asignado
}

func (x *ResultadoReserva) Reset() {
	*x = ResultadoReserva{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservas_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultadoReserva) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoReserva) ProtoMessage() {}

func (x *ResultadoReserva) ProtoReflect() protoreflect.Message {
	mi := &file_reservas_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoReserva.ProtoReflect.Descriptor instead.
func (*ResultadoReserva) Descriptor() ([]byte, []int) {
	return file_reservas_proto_rawDescGZIP(), []int{3}
}

func (x *ResultadoReserva) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResultadoReserva) GetPartySize() int32 {
	if x != nil {
		return x.PartySize
	}
	return 0
}

func (x *ResultadoReserva) GetRequestedPref() string {
	if x != nil {
		return x.RequestedPref
	}
	return ""
}

func (x *ResultadoReserva) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResultadoReserva) GetMesaId() string {
	if x != nil {
		return x.MesaId
	}
	return ""
}

func (x *ResultadoReserva) GetMotivo() string {
	if x != nil {
		return x.Motivo
	}
	return ""
}

func (x *ResultadoReserva) GetMesaTipo() string {
	if x != nil {
		return x.MesaTipo
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservas_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservas_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_reservas_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

var File_reservas_proto protoreflect.FileDescriptor

var file_reservas_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x73, 0x64, 0x22, 0x74, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x72,
	0x74, 0x79, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70,
	0x61, 0x72, 0x74, 0x79, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70,
	0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x22, 0x37, 0x0a, 0x0c, 0x4c, 0x6f,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x73, 0x12, 0x27, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x73,
	0x64, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x52, 0x08, 0x72, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x61, 0x73, 0x22, 0x1f, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0xd2, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x61,
	0x64, 0x6f, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x61, 0x72, 0x74, 0x79, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x70, 0x61, 0x72, 0x74, 0x79, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x25, 0x0a, 0x0e,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x50,
	0x72, 0x65, 0x66, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65,
	0x73, 0x61, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x74, 0x69, 0x76, 0x6f, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x74, 0x69, 0x76, 0x6f, 0x12, 0x1b, 0x0a, 0x09,
	0x6d, 0x65, 0x73, 0x61, 0x5f, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6d, 0x65, 0x73, 0x61, 0x54, 0x69, 0x70, 0x6f, 0x22, 0x2f, 0x0a, 0x10, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x32, 0x3a, 0x0a, 0x0f, 0x52, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x61, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x27, 0x0a,
	0x0a, 0x45, 0x6e, 0x76, 0x69, 0x61, 0x72, 0x4c, 0x6f, 0x74, 0x65, 0x12, 0x10, 0x2e, 0x73, 0x64,
	0x2e, 0x4c, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x73, 0x1a, 0x07, 0x2e,
	0x73, 0x64, 0x2e, 0x41, 0x63, 0x6b, 0x32, 0x3d, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x09, 0x50, 0x65, 0x72,
	0x73, 0x69, 0x73, 0x74, 0x69, 0x72, 0x12, 0x14, 0x2e, 0x73, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x61, 0x64, 0x6f, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x1a, 0x07, 0x2e, 0x73,
	0x64, 0x2e, 0x41, 0x63, 0x6b, 0x32, 0x4d, 0x0a, 0x10, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72,
	0x65, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x09, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x14, 0x2e, 0x73, 0x64, 0x2e, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73,
	0x64, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x64, 0x6f, 0x52, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x61, 0x30, 0x01, 0x42, 0x1c, 0x5a, 0x1a, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_reservas_proto_rawDescOnce sync.Once
	file_reservas_proto_rawDescData = file_reservas_proto_rawDesc
)

func file_reservas_proto_rawDescGZIP() []byte {
	file_reservas_proto_rawDescOnce.Do(func() {
		file_reservas_proto_rawDescData = protoimpl.X.CompressGZIP(file_reservas_proto_rawDescData)
	})
	return file_reservas_proto_rawDescData
}

var file_reservas_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_reservas_proto_goTypes = []interface{}{
	(*Reserva)(nil),          // 0: sd.Reserva
	(*LoteReservas)(nil),     // 1: sd.LoteReservas
	(*Ack)(nil),              // 2: sd.Ack
	(*ResultadoReserva)(nil), // 3: sd.ResultadoReserva
	(*SubscribeRequest)(nil), // 4: sd.SubscribeRequest
}
var file_reservas_proto_depIdxs = []int32{
	0, // 0: sd.LoteReservas.reservas:type_name -> sd.Reserva
	1, // 1: sd.ReservasService.EnviarLote:input_type -> sd.LoteReservas
	3, // 2: sd.RegistroService.Persistir:input_type -> sd.ResultadoReserva
	4, // 3: sd.MonitoreoService.Subscribe:input_type -> sd.SubscribeRequest
	2, // 4: sd.ReservasService.EnviarLote:output_type -> sd.Ack
	2, // 5: sd.RegistroService.Persistir:output_type -> sd.Ack
	3, // 6: sd.MonitoreoService.Subscribe:output_type -> sd.ResultadoReserva
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_reservas_proto_init() }
func file_reservas_proto_init() {
	if File_reservas_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reservas_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reserva); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservas_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoteReservas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservas_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservas_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultadoReserva); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservas_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reservas_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_reservas_proto_goTypes,
		DependencyIndexes: file_reservas_proto_depIdxs,
		MessageInfos:      file_reservas_proto_msgTypes,
	}.Build()
	File_reservas_proto = out.File
	file_reservas_proto_rawDesc = nil
	file_reservas_proto_goTypes = nil
	file_reservas_proto_depIdxs = nil
}
